In [0]:
import pandas as pd
df=pd.read_csv("/Workspace/Users/harshranegame@gmail.com/surat_uncleaned.csv")
df.head()

                                       property_name  ...       price
0          2 BHK Apartment for Sale in Dindoli Surat  ...  ₹33.8 Lac
1           2 BHK Apartment for Sale in Althan Surat  ...  ₹45.4 Lac
2          2 BHK Apartment for Sale in Pal Gam Surat  ...  ₹44.6 Lac
3     2 BHK Apartment for Sale in Jahangirabad Surat  ...    ₹47 Lac
4  2 BHK Apartment for Sale in Orchid Fantasia, P...  ...    ₹45 Lac

[5 rows x 11 columns]

In [0]:
df.shape

(4525, 11)

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   property_name   4525 non-null   object
 1   areaWithType    4525 non-null   object
 2   square_feet     4525 non-null   object
 3   transaction     4421 non-null   object
 4   status          4524 non-null   object
 5   floor           4480 non-null   object
 6   furnishing      4185 non-null   object
 7   facing          3936 non-null   object
 8   description     3154 non-null   object
 9   price_per_sqft  4157 non-null   object
 10  price           4525 non-null   object
dtypes: object(11)
memory usage: 389.0+ KB

In [0]:
df.describe()

                                 property_name  ...           price
count                                     4525  ...            4525
unique                                    1992  ...             841
top     3 BHK Apartment for Sale in Vesu Surat  ...  Call for Price
freq                                        93  ...             173

[4 rows x 11 columns]

In [0]:
df.columns.tolist()

['property_name',
 'areaWithType',
 'square_feet',
 'transaction',
 'status',
 'floor',
 'furnishing',
 'facing',
 'description',
 'price_per_sqft',
 'price']

In [0]:
df.isnull().sum()

property_name        0
areaWithType         0
square_feet          0
transaction        104
status               1
floor               45
furnishing         340
facing             589
description       1371
price_per_sqft     368
price                0
dtype: int64

In [0]:
df.duplicated().sum()

np.int64(109)

In [0]:
df.dtypes

property_name     object
areaWithType      object
square_feet       object
transaction       object
status            object
floor             object
furnishing        object
facing            object
description       object
price_per_sqft    object
price             object
dtype: object

In [0]:
df = df.dropna()

In [0]:
df.isnull().sum()

property_name     0
areaWithType      0
square_feet       0
transaction       0
status            0
floor             0
furnishing        0
facing            0
description       0
price_per_sqft    0
price             0
dtype: int64

In [0]:
df = df.drop_duplicates()

In [0]:
df.duplicated().sum()

np.int64(0)

In [0]:
df["property_name"]=df["property_name"].astype(str)

In [0]:
df.dtypes

property_name     object
areaWithType      object
square_feet       object
transaction       object
status            object
floor             object
furnishing        object
facing            object
description       object
price_per_sqft    object
price             object
dtype: object

In [0]:
print(type(df["price"].iloc[0]))
print(type(df["price_per_sqft"].iloc[0]))
print(type(df["description"].iloc[0]))
print(type(df["facing"].iloc[0]))
print(type(df["furnishing"].iloc[0]))
print(type(df["floor"].iloc[0]))
print(type(df["status"].iloc[0]))
print(type(df["transaction"].iloc[0]))
print(type(df["square_feet"].iloc[0]))
print(type(df["areaWithType"].iloc[0]))
print(type(df["property_name"].iloc[0]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

In [0]:
df["facing"].unique()

array(['West', 'South -West', 'East', '2', 'North - East', '1',
       'Main Road', 'Freehold', 'South - East', 'Garden/Park', '3',
       'North - West', 'South', 'Co-operative Society',
       'Garden/Park, Main Road', 'No', '30 m', 'North', 'Salasar Icon',
       'Gordhan Green Valley Mangalam Park Bldg S',
       'Apt Swaminagar Society', 'Akash', 'Satyam Tower', '4',
       '1 Covered', 'GHB Mukhya Mantri Gruh Yojana', 'Vibrant Eco Park',
       'Gruham Luxuria', '100 m', '1 Open', 'Raj Abhishek City Homes',
       'Gruham Royal Park', 'Prayosha Shine', 'Yes', 'Rajhans Apple',
       'Anjani Enclave', '2 Covered', 'Pool', '900 m',
       'Vaishnodevi Amour Jahagirabad', '20 m', '10 m', '25 m',
       'Swagat Clifton', 'Vaishnodevi Ideal Homes', '7 m',
       '45 X 14 ft Sqft', 'Pool, Garden/Park, Main Road', 'Santvan Lexon',
       '5', 'Atlanta Sky Desk', 'Nakshatra Platinum', '6',
       'Vasant Vihar Township', 'Shalibhadra Complex', 'Green Leaf',
       'Garden/Park, Pool', 'Shreepad Ethics',
       'Garden/Park, Pool, Main Road', 'Santvan Seron', '15 m',
       'Nakshatra Galaxia', '150 m', 'Rajhans Synfonia', 'Oliva Height',
       'Mahaveer Nagar', '4 m', 'Shreepad Infinia', 'Palladium Sky',
       '3 Covered', 'Prestige manor', 'Green City Gold',
       'Avadh Shangrila', '45 X', '6 m', 'Atithi Western Oasis',
       'Harmony', 'Cellestial Dreams', 'Nandanvan III', 'aventis ofira',
       '135 X', '8 m', '12 m', 'Power Of Attorney', '20275 m'],
      dtype=object)

In [0]:
valid_directions = ["East", "West", "North", "South","South -West","North - East","South - East","North - West"]
df["facing"] = df["facing"].where(df["facing"].isin(valid_directions))

In [0]:
df["facing"].unique()

array(['West', 'South -West', 'East', nan, 'North - East', 'South - East',
       'North - West', 'South', 'North'], dtype=object)

In [0]:
df["facing"].value_counts(dropna=False)

facing
East            1128
NaN              728
South -West      322
North - East     210
North             79
West              72
South - East      41
South             25
North - West      20
Name: count, dtype: int64

In [0]:
df["facing"] = df["facing"].fillna("Unknown")

In [0]:
df["facing"].value_counts(dropna=False)

facing
East            1128
Unknown          728
South -West      322
North - East     210
North             79
West              72
South - East      41
South             25
North - West      20
Name: count, dtype: int64

In [0]:
df["furnishing"].unique()

array(['Unfurnished', 'Semi-Furnished', '2', 'Anand Aspire', 'Furnished',
       '1', 'East', '1 Covered,', '1 Covered', 'Freehold', 'West',
       'Main Road', 'Co-operative Society', 'North',
       'Pool, Garden/Park, Main Road', 'Garden/Park, Main Road', '7 m',
       '30 m', '3', '50 Covered,', '12 m', '4', '2 Covered,', 'Congo',
       '1 Open', 'North - East', 'Vaishnodevi Ideal Homes',
       'Santvan Lexon', 'Sangini Epitome', 'South -West', '2 Covered',
       '5', '50 Open', 'South', '10 m', 'Sattvam', 'Pramukh Amaya',
       'Sun Sarvam', 'Garden/Park', '3 Covered', '2 Open', '6 m',
       'Avadh Kimberly', 'Happy Glorious', 'Freedom Tower',
       'Surya Signature', '6', 'Green Valley Row House', '10 Covered,',
       'Ambience', 'Milestone Pristine', 'Bblossom The Presidency'],
      dtype=object)

In [0]:
valid_furnishings = ["Semi-Furnished", "Furnished", "Unfurnished"]
df["furnishing"] = df["furnishing"].where(df["furnishing"].isin(valid_furnishings))

In [0]:
df["furnishing"].unique()

array(['Unfurnished', 'Semi-Furnished', nan, 'Furnished'], dtype=object)

In [0]:
df["furnishing"].value_counts(dropna=False)

furnishing
Unfurnished       1689
NaN                480
Furnished          247
Semi-Furnished     209
Name: count, dtype: int64

In [0]:
df["floor"].unique()

array(['5 out of 10', '6 out of 14', '5 out of 13', 'Unfurnished',
       'New Property', '3 out of 14', '6 out of 13', '1 out of 1',
       '7 out of 10', '1 out of 13', '3 out of 5', '2 out of 5',
       '5 out of 5', 'Resale', 'Ground out of 1', '1 out of 5',
       '7 out of 14', '9 out of 14', '5 out of 12', '7 out of 13',
       'Freehold', '12 out of 14', '3 out of 12', '10 out of 14',
       '13 out of 14', '4 out of 14', '6 out of 10', '2 out of 4',
       '1 out of 4', '3 out of 4', '9 out of 13', '4 out of 4',
       '4 out of 10', 'Ground out of 2', '5 out of 6', '4 out of 5',
       '2 out of 7', '7 out of 7', 'Ground out of 3', '3 out of 10',
       '4 out of 8', '1 out of 6', '5 out of 14', '5 out of 7',
       '8 out of 12', '7 out of 12', '1 out of 12', '3 out of 9',
       '11 out of 12', '6 out of 12', '2 out of 12', '8 out of 13',
       '11 out of 11', '3 out of 3', '3 out of 7', '4 out of 13',
       '8 out of 8', '2 out of 3', 'Ground out of 7', '2 out of 10',
       '1 out of 2', '4 out of 6', '3 out of 6', '6 out of 11',
       '4 out of 15', '10 out of 13', 'Ground out of 4', '13 out of 13',
       '5 out of 8', '14 out of 14', '2', '1 out of 11', '1 out of 10',
       '9 out of 10', '8 out of 9', '3', '1 out of 3', '4 out of 7',
       '11 out of 13', 'Ground out of 13', '6 out of 8', '8 out of 14',
       '8 out of 10', '4 out of 19', '2 out of 6', '11 out of 14',
       '5 out of 15', '15 out of 19', 'Co-operative Society',
       '4 out of 11', '9 out of 12', '7 out of 9', '7 out of 19',
       '10 out of 10', 'Lower Basement out of 14', '7 out of 11',
       '6 out of 15', '5 out of 11', '6 out of 19', '2 out of 11',
       '4 out of 12', '9 out of 19', '9 out of 15', '2 out of 2',
       '1 out of 7', '16 out of 19', '18 out of 19', '7 out of 8',
       '2 out of 13', '3 out of 11', '1 out of 9', '1 out of 15',
       '10 out of 20', '13 out of 15', '1 out of 14', '20 out of 21',
       '3 out of 13', '8 out of 19', '2 out of 14', '10 out of 12',
       '7 out of 15', 'Lower Basement out of 5', '12 out of 13',
       '2 out of 9', '9 out of 9', '10 out of 11', '4 out of 9',
       '12 out of 12', '15 out of 21', '6 out of 9', '12 out of 15',
       '15 out of 15', '8 out of 15', '11 out of 15', '8 out of 11',
       '10 out of 15', '13 out of 19', '3 out of 15', '14 out of 19',
       '2 out of 15', '8 out of 20', '18 out of 21', '6 out of 6',
       '5 out of 20', '15 out of 18', '10 out of 21', '5 out of 19',
       '5 out of 16', '10 out of 19', '17 out of 20', '5 out of 18',
       '15 out of 20', 'Ground out of 10', '10 out of 18', '7 out of 20',
       '11 out of 20', '17 out of 18', '7 out of 17', '9 out of 25',
       '6 out of 20', '6 out of 18', 'Upper Basement out of 3',
       '9 out of 20', '4 out of 18', '9 out of 21', '4 out of 21',
       '9 out of 11', '6 out of 7', '19 out of 19', '17 out of 19',
       '7 out of 18', '20 out of 20', '4 out of 20', '9 out of 18',
       'Ground out of 12', '3 out of 18', '16 out of 20', '2 out of 19',
       '16 out of 18', '12 out of 19', '3 out of 19', '3 out of 20',
       '1 out of 20', '2 out of 17', '9 out of 17', '1 out of 18'],
      dtype=object)

In [0]:
import re

pattern = r'^(Ground|Lower Basement|Upper Basement|\d+)\s+out of\s+\d+$'

df["floor"] = df["floor"].where(df["floor"].astype(str).str.match(pattern))

In [0]:
df["floor"].value_counts(dropna=False)

floor
NaN             445
5 out of 13     191
7 out of 13     118
6 out of 13     106
5 out of 12      99
               ...
7 out of 20       1
11 out of 20      1
3 out of 6        1
7 out of 17       1
1 out of 18       1
Name: count, Length: 180, dtype: int64

In [0]:
df = df.dropna(subset=["floor"])

In [0]:
df["floor"].value_counts(dropna=False)

floor
5 out of 13     191
7 out of 13     118
6 out of 13     106
5 out of 12      99
6 out of 12      80
               ...
7 out of 20       1
11 out of 20      1
3 out of 6        1
7 out of 17       1
1 out of 18       1
Name: count, Length: 179, dtype: int64

In [0]:
df["property_name"].unique()

array(['2 BHK Apartment for Sale in Dindoli Surat',
       '2 BHK Apartment for Sale in Althan Surat',
       '2 BHK Apartment for Sale in Pal Gam Surat',
       '2 BHK Apartment for Sale in Jahangirabad Surat',
       '2 BHK Apartment for Sale in Palanpur Surat',
       '1 BHK  House for Sale in Kim Surat',
       '2 BHK Apartment for Sale in NavYug College Surat',
       '2 BHK Apartment for Sale in Adajan Surat',
       '3 BHK Apartment for Sale in Dindoli Surat',
       '3 BHK Apartment for Sale in Mota Varachha Surat',
       '1 BHK Apartment for Sale in Ramnagar Surat',
       '2 BHK Builder Floor for Sale in Amroli Surat',
       '1 BHK  House for Sale in Palsana Surat',
       '3 BHK Apartment for Sale in Jahangirabad Surat',
       '2 BHK Apartment for Sale in Shivalik Height Surat',
       '2 BHK Apartment for Sale in Bamroli Surat',
       '2 BHK Apartment for Sale in Godadara Surat',
       '3 BHK Apartment for Sale in Palanpur Surat',
       '1 BHK Apartment for Sale in Jahangirabad Surat',
       '  Office Space for Sale in Vesu Surat',
       '3 BHK Apartment for Sale in Jahangir Pura Surat',
       '  Office Space for Sale in Nanpura Surat',
       '2 BHK Apartment for Sale in Swagat Home Surat',
       '1 BHK Apartment for Sale in Palanpur Surat',
       '1 BHK Apartment for Sale in Jahangir Pura Surat',
       '2 BHK  House for Sale in Nansad Surat',
       '2 BHK Apartment for Sale in Jahangir Pura Surat',
       '1 BHK Apartment for Sale in Bhesan Road Surat',
       '1 BHK Apartment for Sale in Katar Gam Surat',
       '1 BHK Apartment for Sale in Bhatar Surat',
       '1 BHK Apartment for Sale in Adajan Surat',
       '2 BHK Builder Floor for Sale in Varachha Surat',
       '2 BHK Builder Floor for Sale in Nana Varachha Surat',
       '2 BHK Apartment for Sale in Citylight Area Surat',
       '1 BHK  House for Sale in Sayan Surat',
       '2 BHK Apartment for Sale in Aarav Apartment Surat',
       '1 BHK Apartment for Sale in Ram Pura Surat',
       '2 BHK Apartment for Sale in Varachha Surat',
       '4 BHK Apartment for Sale in Bhatar Surat',
       '2 BHK Apartment for Sale in Nana Varachha Surat',
       '2 BHK Apartment for Sale in Lambe Hanuman Road Surat',
       '2 BHK  House for Sale in Olpad Sayan Road Surat',
       '3 BHK  House for Sale in Kamrej Surat',
       '1 BHK Builder Floor for Sale in Olpad Surat',
       '2 BHK Penthouse for Sale in L P Savani Surat',
       '2 BHK Apartment for Sale in Honey Park Surat',
       '2 BHK Apartment for Sale in 503RIDDHI SIDDHI RESIDENCY Surat',
       '2 BHK Apartment for Sale in vatika township Surat',
       '2 BHK Apartment for Sale in Rander Road Surat',
       '2 BHK Builder Floor for Sale in devdhgam Surat',
       '1 BHK Apartment for Sale in pavitra residency Surat',
       '2 BHK Apartment for Sale in Mangal pushp apartment,  L P SAVANI CIRCLE adajan Surat',
       '1 BHK Apartment for Sale in Udhna Surat',
       '2 BHK Apartment for Sale in vraj vihar complex koli street adajan gam Surat',
       '2 BHK  House for Sale in Velanja Surat',
       '2 BHK Builder Floor for Sale in Jahangirabad Surat',
       '2 BHK  House for Sale in Dindoli Surat',
       '1 BHK Builder Floor for Sale in Kim Surat',
       '2 BHK Builder Floor for Sale in Palanpur Surat',
       '2 BHK Apartment for Sale in Rustampura Surat',
       '3 BHK  House for Sale in Navagam Surat',
       '2 BHK Builder Floor for Sale in Adajan Surat',
       '1 BHK Apartment for Sale in Amroli Surat',
       '2 BHK Apartment for Sale in Amroli Surat',
       '1 BHK Builder Floor for Sale in Bhestan Surat',
       '2 BHK Builder Floor for Sale in Pasodara Surat',
       '1 BHK  House for Sale in Velanja Surat',
       '1 BHK Builder Floor for Sale in Amroli Surat',
       '3 BHK Apartment for Sale in Gopi Pura Surat',
       '2 BHK Apartment for Sale in Katar Gam Surat',
       '3 BHK  House for Sale in Palsana Surat',
       '1 BHK Apartment for Sale in Minaxi Wadi Surat',
       '1 BHK Apartment for Sale in suman ashish Surat',
       '1 BHK Builder Floor for Sale in Kadodar Surat',
       '2 BHK Apartment for Sale in Palanpur Gam Surat',
       '2 BHK Apartment for Sale in Rajhans Platinum, Palanpur Surat',
       '2 BHK Apartment for Sale in Swagat Clifton, Bhimrad Surat',
       '1 BHK  House for Sale in Dindoli Surat',
       '2 BHK Apartment for Sale in Piplod Surat',
       '2 BHK Apartment for Sale in Sangini Swaraj, Jahangir Pura Surat',
       '3 BHK Apartment for Sale in Penttagon Residency, Palanpur Jakatnaka Surat',
       '2 BHK  House for Sale in Unn Patiya Surat',
       '3 BHK  House for Sale in Dindoli Surat',
       '1 BHK Builder Floor for Sale in Nan Pura Surat',
       '1 BHK Apartment for Sale in 103 AjithNath Awas Surat',
       '2 BHK Apartment for Sale in Mota Varachha Surat',
       '2 BHK Apartment for Sale in Salasar Icon, Dindoli Surat',
       '2 BHK Apartment for Sale in Swapna Srusthi Residency Plots, Bhestan Surat',
       '2 BHK Apartment for Sale in Mahavir Residency, Rander Road Surat',
       '2 BHK Apartment for Sale in Stuti Empress, Palanpur Surat',
       '2 BHK Apartment for Sale in Parishram Park, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Ramaa Residency, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Kailash Nagar Surat',
       '2 BHK Apartment for Sale in Nakshatra Solitaire, Palanpur Surat',
       '2 BHK Apartment for Sale in Siddhi Vinayak Heights, Pal Surat',
       '2 BHK Apartment for Sale in Vaidehi Heights, Dindoli Surat',
       '2 BHK  House for Sale in Chalthan Surat',
       '2 BHK Apartment for Sale in Meera Avenue, Khadsad Surat',
       '1 BHK Apartment for Sale in Angan Appartment Surat',
       '1 BHK Apartment for Sale in Ambika Township, Dindoli Surat',
       '1 BHK Penthouse for Sale in Echo Point, Althan Surat',
       '2 BHK Apartment for Sale in Samruddhi Apartment, Gopi Pura Surat',
       '2 BHK Apartment for Sale in Siddhi Vinayak Residency, Sachin Surat',
       '2 BHK Apartment for Sale in Sumeru Sky Residency, Mota Varachha Surat',
       '2 BHK  House for Sale in Olpad Surat',
       '2 BHK Apartment for Sale in Gordhan Green Valley Mangalam Park Bldg S, Dindoli Surat',
       '2 BHK Apartment for Sale in Apt Swaminagar Society, Bhatar Surat',
       '2 BHK Apartment for Sale in Nilkanth Seven Homes, Dindoli Surat',
       '1 BHK Apartment for Sale in Athwalines Surat',
       '1 BHK Apartment for Sale in star pavitra nagri kholvad Surat',
       '2 BHK Apartment for Sale in JT JT Stuti Icon, Adajan Surat',
       '2 BHK Apartment for Sale in Katargam Surat',
       '1 BHK Apartment for Sale in Gopi Pura Surat',
       '1 BHK Apartment for Sale in Kadodar Surat',
       '1 BHK Apartment for Sale in Satyam Tower, Udhna Surat',
       '4 BHK  House for Sale in Mahalaxmi Society Surat',
       '1 BHK Apartment for Sale in Ghod Dod Rd Surat',
       '2 BHK  House for Sale in Kamrej Char Rasta Surat',
       '2 BHK Apartment for Sale in Amber Palace, Nan Pura Surat',
       '2 BHK Penthouse for Sale in Gruham Luxuria, Masma Village Surat',
       '2 BHK Apartment for Sale in Amber Palace, Kamrej Char Rasta Surat',
       '2 BHK Apartment for Sale in Hazira Road Surat',
       '2 BHK Apartment for Sale in Bhumi complex Surat',
       '2 BHK Apartment for Sale in GHB Mukhya Mantri Gruh Yojana, Jahangirabad Surat',
       '1 BHK Builder Floor for Sale in Adajan Surat',
       '3 BHK Apartment for Sale in Adajan Surat',
       '2 BHK Apartment for Sale in Rajhans Gold Residency, Jahangir Pura Surat',
       '2 BHK Apartment for Sale in SK Apt Patel Colony Surat',
       '2 BHK  House for Sale in Gruham Luxuria, Masma Village Surat',
       '2 BHK Apartment for Sale in Ambica Arihant Heights, Palan Pur Patiya Surat',
       '2 BHK Apartment for Sale in 3K Prime Shyam Enclave, Jahangir Pura Surat',
       '2 BHK Apartment for Sale in Jay Mahakali Krupa Apartment Surat',
       '3 BHK Penthouse for Sale in Lajpur Surat',
       '2 BHK Builder Floor for Sale in Near Arya Club Tena Village Surat',
       '1 BHK Apartment for Sale in Kailash Nagar Surat',
       '1 BHK Builder Floor for Sale in Katar Gam Surat',
       '2 BHK  House for Sale in Kawas Surat',
       '5 BHK  House for Sale in Sarsana Surat',
       '1 BHK Apartment for Sale in Suman Vihar Surat',
       '2 BHK Builder Floor for Sale in Alkapuri Surat',
       '2 BHK Builder Floor for Sale in Citylight Area Surat',
       '1 BHK Apartment for Sale in Subhash Nagar Surat',
       '2 BHK Apartment for Sale in JT Stuti Highland, Palanpur Surat',
       '3 BHK Apartment for Sale in Raj Abhishek City Homes, Sachin Surat',
       '2 BHK Apartment for Sale in Aksharkunj apartment, Udhna Surat',
       '2 BHK Apartment for Sale in Radhakishan Flats Surat',
       '2 BHK  House for Sale in Udhana Surat',
       '1 BHK Apartment for Sale in Karmabhoomi Complex, Adajan Surat',
       '2 BHK Apartment for Sale in Palanpur Jakatnaka Surat',
       '2 BHK Apartment for Sale in JT Stuti Icon, Palanpur Surat',
       '1 BHK Apartment for Sale in Bhagal Surat',
       '1 BHK Apartment for Sale in GREEN HOUSE APARTMENT Surat',
       '2 BHK Builder Floor for Sale in Vakaneda Chalthan Surat',
       '2 BHK Apartment for Sale in Bagumara Surat',
       '2 BHK Apartment for Sale in Devadh Surat',
       '3 BHK Apartment for Sale in AG Sentosa Enclave, Godadara Surat',
       '1 BHK Apartment for Sale in Pal Road Surat',
       '2 BHK Apartment for Sale in Bhakti Shiv Dhara Residency, Mota Varachha Surat',
       '2 BHK Apartment for Sale in Green Paradise, Jahangirabad Surat',
       '1 BHK Apartment for Sale in Omkar Residency, Palan Pur Patiya Surat',
       '4 BHK  House for Sale in Pal Surat',
       '2 BHK Builder Floor for Sale in Sachin Surat',
       '1 BHK Apartment for Sale in Nil Gagan Apartment, Athwa Gate Surat',
       '2 BHK Apartment for Sale in Neelkanth Residency, Palanpur Gam Surat',
       '2 BHK Apartment for Sale in Stuti Empress, Palan Pur Patiya Surat',
       '2 BHK Apartment for Sale in Rajhans Apple, Palanpur Gam Surat',
       '1 BHK Builder Floor for Sale in Umra Surat',
       '3 BHK Apartment for Sale in Amroli Surat',
       '2 BHK Apartment for Sale in Anjani Enclave, Dahin Nagar Surat',
       '2 BHK Apartment for Sale in Happy Elegance, Vesu Surat',
       '2 BHK Builder Floor for Sale in Haripura Surat',
       '2 BHK Builder Floor for Sale in Majura Gate Surat',
       '  Office Space for Sale in Pal Road Surat',
       '2 BHK Apartment for Sale in Society Surat',
       '2 BHK Apartment for Sale in Ghod Dod Road Surat',
       '1 BHK Apartment for Sale in Athwa Surat',
       '2 BHK Apartment for Sale in Ram Pura Surat',
       '2 BHK Apartment for Sale in Salabatura Surat',
       '2 BHK Apartment for Sale in Ravi Darshan Apartment, Citylight Area Surat',
       '1 BHK Builder Floor for Sale in Kamrej Surat',
       '1 BHK  House for Sale in Kamrej Surat',
       '2 BHK Apartment for Sale in Akshar enterprise intercity complex Dumbhal Surat',
       '2 BHK Apartment for Sale in Shrungal Palace, Bamroli Surat',
       '1 BHK Builder Floor for Sale in Pal Surat',
       '2 BHK Apartment for Sale in Swayam Residency Surat',
       '2 BHK Apartment for Sale in Athawa Lines Surat',
       '2 BHK Apartment for Sale in Nest Buildcon Rhythm Residency and Plaza, Amroli Surat',
       '3 BHK  House for Sale in Astoria Greens Surat',
       '2 BHK Apartment for Sale in Bhatar Surat',
       '2 BHK Builder Floor for Sale in Palsana Kadodara Highway Surat',
       '1 BHK Apartment for Sale in Nova Residency, Jahangir Pura Surat',
       '1 BHK Apartment for Sale in Rander Road Surat',
       '2 BHK Apartment for Sale in Vaishnodevi Amour Jahagirabad, Jahangirabad Surat',
       '1 BHK  House for Sale in Palan Pur Patiya Surat',
       '2 BHK Apartment for Sale in Anand Mahal Road Surat',
       '3 BHK Apartment for Sale in Kamrej char charasta  Surat',
       '2 BHK Apartment for Sale in Nan Pura Surat',
       '2 BHK Builder Floor for Sale in Nan Pura Surat',
       '2 BHK Apartment for Sale in Gordhan Green Valley, Dindoli Surat',
       '2 BHK  House for Sale in Parvat Patiya Surat',
       '1 BHK Apartment for Sale in indrajit Apartment near Milk Palace Surat',
       '1 BHK Apartment for Sale in Millenium Park, Dindoli Surat',
       '  Office Space for Sale in Samarth Park, Adajan Surat',
       '3 BHK Apartment for Sale in Pragati Nagar, Piplod Surat',
       '2 BHK Apartment for Sale in L P Savani Surat',
       '2 BHK  House for Sale in Kim Surat',
       '3 BHK Apartment for Sale in Katargam Surat',
       '2 BHK Apartment for Sale in Santvan Skyon, Palanpur Surat',
       '2 BHK Apartment for Sale in Shagun Residency, Jahangir Pura Surat',
       '1 BHK Apartment for Sale in Palan Pur Patiya Surat',
       '2 BHK Apartment for Sale in Vesu Surat',
       '1 BHK Apartment for Sale in Nanpura Surat',
       '3 BHK Apartment for Sale in Muktanand Nagar Surat',
       '1 BHK Builder Floor for Sale in Jolva Surat',
       '2 BHK Apartment for Sale in Anand Aspire, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Orchid Gardenia, Palanpur Surat',
       '3 BHK Apartment for Sale in Godadara Surat',
       '  Office Space for Sale in VIP Road Surat',
       '1 BHK Apartment for Sale in Dindoli Surat',
       '2 BHK  House for Sale in Palsana Surat',
       '1 BHK Apartment for Sale in Vesu Surat',
       '2 BHK Apartment for Sale in Surat Surat',
       '2 BHK Apartment for Sale in Shiv Samarth 1, Pal Gam Surat',
       '  Office Space for Sale in Lal Gate Surat',
       '2 BHK Apartment for Sale in Agam residensy Surat',
       '2 BHK Apartment for Sale in Pal Surat',
       '2 BHK Builder Floor for Sale in Katar Gam Surat',
       '2 BHK Apartment for Sale in Vaishnodevi Residency, Dahin Nagar Surat',
       '3 BHK  House for Sale in Dandi Road Surat',
       '2 BHK Apartment for Sale in Udhna Surat',
       '2 BHK Apartment for Sale in Govindji Park, Umra Surat',
       '3 BHK Apartment for Sale in Penttagon, Palanpur Gam Surat',
       '1 BHK Apartment for Sale in Orchid Infinity, Palan Pur Patiya Surat',
       '2 BHK Apartment for Sale in Swicon Wings, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Swagat Clifton, Althan Surat',
       '4 BHK  House for Sale in Udhana Surat',
       '2 BHK Apartment for Sale in Griva Shivalik Residency, Bhimrad Surat',
       '2 BHK Apartment for Sale in Siddhi Vinayak Elements, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Vanakala Surat',
       '2 BHK Apartment for Sale in Shubham Residency, Pal Surat',
       '2 BHK Apartment for Sale in Shree Krishna Dreams, Godadara Surat',
       '2 BHK Apartment for Sale in Crystal Avenue, Palanpur Gam Surat',
       '2 BHK  House for Sale in Masma Village Surat',
       '2 BHK Apartment for Sale in Narayan Coral Heights, Palanpur Surat',
       '1 BHK Apartment for Sale in Parvat Patiya Surat',
       '2 BHK Apartment for Sale in Minaxi Wadi Surat',
       '2 BHK Apartment for Sale in Vaishnodevi Ideal Homes, Bhesan Gam Surat',
       '3 BHK Apartment for Sale in Green City, Pal Surat',
       '2 BHK Apartment for Sale in Orchid Fantasia, Palanpur Surat',
       '3 BHK Apartment for Sale in Vanakala Surat',
       '2 BHK Apartment for Sale in Swagat Callista, Bamroli Surat',
       '2 BHK Apartment for Sale in Times Galaxy, Bhesan Gam Surat',
       '2 BHK Apartment for Sale in Chanchal Rang Raag Residency, Jahangir Pura Surat',
       '  Office Space for Sale in SNS Arista, Vesu Surat',
       '3 BHK  House for Sale in Narthan Surat',
       '2 BHK Apartment for Sale in Vaishnodevi Ideal Homes, Dahin Nagar Surat',
       '2 BHK Apartment for Sale in Green City, Pal Surat',
       '2 BHK Apartment for Sale in Shubham Pearl, Palanpur Surat',
       '1 BHK Apartment for Sale in Ramaa Residency, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Sumerru Sky Leaf, Palanpur Surat',
       '2 BHK Apartment for Sale in The Capital, Palanpur Surat',
       '1 BHK Apartment for Sale in S2N Orchid Ventura, Palan Pur Patiya Surat',
       '  Office Space for Sale in Rajhans Olympia, Bhatar Surat',
       '2 BHK Apartment for Sale in Anjani Residency, Jahangir Pura Surat',
       '2 BHK Apartment for Sale in Nakshatra Embassy, Palanpur Surat',
       '2 BHK Apartment for Sale in gail tower Surat',
       '2 BHK Apartment for Sale in Bhimrad Surat',
       '2 BHK Apartment for Sale in Coral Heights, Vesu Canal Road Surat',
       '2 BHK Apartment for Sale in Vaishnodevi Kingswood, Jahangirabad Surat',
       '2 BHK Apartment for Sale in LP Savani Surat',
       '3 BHK Apartment for Sale in Kelly La Maison, Vanakala Surat',
       '2 BHK Apartment for Sale in Bhesan Gam Surat',
       '2 BHK Apartment for Sale in Aagam Prestige, Magdalla Surat',
       '2 BHK Apartment for Sale in Devshree Benito, Jahangir Pura Surat',
       '2 BHK Apartment for Sale in Nakshatra Nebula, Jahangirabad Surat',
       '3 BHK  House for Sale in Masma Village Surat',
       '1 BHK Apartment for Sale in Palanpur Gam Surat',
       '1 BHK Apartment for Sale in Swicon Wings, Jahangirabad Surat',
       '3 BHK Apartment for Sale in Shri Bhakti Dharm Township, Jahangirabad Surat',
       '1 BHK Apartment for Sale in dream home real estate Surat',
       '2 BHK Apartment for Sale in Divine Residency, Palanpur Gam Surat',
       '1 BHK Apartment for Sale in Shayona Janki Residency, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Anand Avenue, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Shyam enclave, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Green Tulip, Jahangirabad Surat',
       '2 BHK Apartment for Sale in Orchid Blossom, Palanpur Surat',
       '1 BHK Apartment for Sale in Orchid Blossom, Palanpur Surat',
       '2 BHK Apartment for Sale in Green City, Bhatha Surat',
       '3 BHK Apartment for Sale in Santvan Lexon, Palanpur Surat',
       '3 BHK Apartment for Sale in Bamroli Surat',
       '4 BHK Builder Floor for Sale in Varachha Main Road Surat',
       '3 BHK  House for Sale in Hajira Surat',
       '3 BHK Apartment for Sale in Surat Surat',
       '3 BHK Apartment for Sale in Bhimrad Surat',
       '2 BHK Apartment for Sale in Gauravpath Road Surat',
       '3 BHK Apartment for Sale in Piplod Surat',
       '3 BHK Apartment for Sale in Pal Surat',
       '3 BHK Apartment for Sale in Parley Point Surat',
       '2 BHK Apartment for Sale in sanctum Surat',
       '2 BHK  House for Sale in Adajan Surat',
       '3 BHK Apartment for Sale in Vesu Surat',
       '2 BHK Apartment for Sale in Parley Point Surat',
       '4 BHK  House for Sale in Kamrej Char Rasta Surat',
       '  Showroom for Sale in Mandvi Surat',
       '2 BHK Apartment for Sale in Santvan Lexon, Palanpur Surat',
       '2 BHK  House for Sale in Morarji Nagar Surat',
       '3 BHK Apartment for Sale in WESTERN CITY, Adajan Surat',
       '2 BHK Apartment for Sale in Western Heights, Pal Surat',
       '3 BHK  House for Sale in darpan row house Surat',
       '3 BHK Apartment for Sale in Silver Spring Appartment Surat',
       '4 BHK  House for Sale in Amroli Surat',
       '4 BHK  House for Sale in Dindoli Surat',
       '4 BHK Apartment for Sale in Rajworld Residency Surat',
       '1 BHK  House for Sale in Rustampura Surat',
       '3 BHK Apartment for Sale in Surat City Surat',
       '3 BHK Apartment for Sale in Althan Surat',
       '3 BHK  House for Sale in Jahangirabad Surat',
       '3 BHK Apartment for Sale in Kailash Nagar Surat',
       '2 BHK  House for Sale in Nanpura Surat',
       '8 BHK  House for Sale in Aman Nagar Surat',
       '4 BHK  House for Sale in Bhestan Surat',
       '3 BHK Apartment for Sale in Suryoday complex Adajan Surat',
       '3 BHK  House for Sale in Mota Varachha Surat',
       '2 BHK  House for Sale in Katargam Surat',
       '4 BHK Apartment for Sale in Adajan Surat',

In [0]:
df.to_csv("cleaned_data.csv", index=False)